require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Kalzi' do
  config = use_native_modules!
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  use_react_native!(:path => config["reactNativePath"])

  target 'KalziTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#   use_flipper!({'Flipper' => '0.79.0'})
  # post_install do |installer|
  #   installer.pods_project.targets.each do |target|
  #     target.build_configurations.each do |config|
  #       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
  #     end
  #    end
  #   flipper_post_install(installer)
  # end
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
end
end

target 'Kalzi-tvOS' do
  # Pods for Kalzi-tvOS

  target 'Kalzi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
